### ISSUE TITLE
🎞️gif 따기

### ISSUE THREAD

**Issue by JOSuYeoM** [FRONTENDSCHOOL6/escape12#180]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/a99c714c-cf0f-4983-b0f3-f230fa585ce6)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/2111ea8d-bc46-4b9f-905d-6cdaf91489c5)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/276ce055-1cbc-4575-bd6c-3662e7a4f998)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/e30c2693-3514-4a57-ba33-73e675545f77)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/17d2d9a1-3b09-4981-a8ff-f5a96888f581)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/c2868ef3-37a5-466f-95bc-8e52f2fa8481)

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/56884a87-5bc6-4dd7-8a95-923bd95c94a3)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/5db73846-5c51-4375-b13a-4751d79b817e)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/91b7412a-fac4-4bda-9b34-d1aa09855be8)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/a2634606-fdad-4844-9740-6d7328d24a22)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/1e3358b9-3fed-4886-81e4-f80268a15d5e)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/f961cc40-12c1-479e-bc03-558ba3c46b1d)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/0dfe95c1-4abd-4bfb-a4ae-d865dc17917a)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/fb65aabb-a92e-4c68-9fef-4c50cd66993a)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/462426c6-af3c-4b3b-94b0-339f05ffbde6)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/ec22a736-cf65-4f97-baac-6c85d760f607)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/35a8182c-2f70-4f9d-98af-d21f0a68bd53)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/ee32ed84-d320-470e-8064-c994b08a4e1e)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/db4a3897-e042-4cbc-bf1e-163538d21c16)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/e9260bb2-0063-4faf-b071-8b14303f8e8a)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/b5f92e17-360e-43a3-ae30-d84e5fdafa8c)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/b51a0401-d6fe-42b3-a395-81af9632b490)

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/f4bd5c6c-eed1-427c-ae17-80deb14c9340)

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/cec78a0e-edf7-4e08-9471-c30cdcabdc1c)

**Comment by skawls** [comment]
![ezgif com-video-to-gif (4)](https://github.com/FRONTENDSCHOOL6/escape12/assets/134567421/21d2423b-19c8-49bb-a91e-234797888add)

**Comment by skawls** [comment]
![ezgif com-video-to-gif (3)](https://github.com/FRONTENDSCHOOL6/escape12/assets/134567421/0a20738b-fc9c-4b6c-8f70-b48362b4180e)
![ezgif com-video-to-gif (2)](https://github.com/FRONTENDSCHOOL6/escape12/assets/134567421/8a20a9e9-49f3-495c-baa2-a87504d095b5)
![ezgif com-video-to-gif](https://github.com/FRONTENDSCHOOL6/escape12/assets/134567421/44da9e0c-75d3-4f7f-a1e7-866177fc7115)
