### ISSUE TITLE
✨Spinner.jsx

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#30]

**Comment by KIMGEUNDU** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/126174401/90bf0c99-4ea6-488d-95ad-dafe822bac3a)


스피너 만들었어용 gif 가 끊겨보이는데 실제로는 부드러워용

**Comment by JOSuYeoM** [comment]
우와 좋아요
