### ISSUE TITLE
호빵체랑 SUIT체

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#45]
😀 피그마에서 폰트 직접 수정하고싶으시면 다운받아서 로컬에 저장해주세용

**Comment by KIMGEUNDU** [comment]
[호빵체스위트체.zip](https://github.com/FRONTENDSCHOOL6/escape12/files/12570151/default.zip)

**Comment by skawls** [comment]
적용 했습니다😀

**Comment by JOSuYeoM** [comment]
저도 적용했어요 😎
