### ISSUE TITLE
🔐 2주차 개인진도 🔐

### ISSUE THREAD

**Issue by KIMGEUNDU** [FRONTENDSCHOOL6/escape12#49]
### 전체 (최소 기준)

1. UI 완벽하게 완성
2. 데이터 올리기, 가져오기 
3. 포켓호스트 데이터 필드 완벽하게 만들기

**Comment by skawls** [comment]
### Comment페이지 완성
- [ ] Community 페이지에 등록된 게시글 불러오기 , 각 게시글별 댓글 상태 불러오기
- [ ] 댓글 등록 클릭 시 상태 업데이트
😂

**Comment by KIMGEUNDU** [comment]
### 전체 (최소 기준)

1. UI 완벽하게 완성
2. 데이터 올리기, 가져오기 
3. 포켓호스트 데이터 필드 완벽하게 만들기

**Comment by JOSuYeoM** [comment]
### 맡은 페이지들 완성
- [ ] 데이터 불러오기, 올리기 꼭! 해내기
- [ ] 전체 페이지 UI 완성 (9.13(수)까지) 🤔
