### ISSUE TITLE
🔍웹 표준, 웹 접근성 확인

### ISSUE THREAD

**Issue by JOSuYeoM** [FRONTENDSCHOOL6/escape12#73]

**Comment by JOSuYeoM** [comment]
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/f61ba10d-f7f0-4045-a3d1-33f08760398a)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/e16159c7-85f1-4f03-a7f0-c7e02e39e142)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/8c945c70-1d71-4d01-bf41-3d1b0578e110)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/f902e9fe-c715-4df8-a9a4-39545d84ebb0)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/a0408996-20e0-4131-b411-1ab353b42559)
![Image](https://github.com/FRONTENDSCHOOL6/escape12/assets/86372549/559dab9e-0b2d-4126-9717-82199ad1cb05)

**Comment by skawls** [comment]
모든페이지 접근성 완료
