### ISSUE TITLE
❓9월 19일 트러블슈팅방 11:00 - 11:25 질문

### ISSUE THREAD

**Issue by JOSuYeoM** [FRONTENDSCHOOL6/escape12#88]
Q. 페이지네이션 - 리액트쿼리
Q. 이미지 최적화
Q. useState 사용 시 성능 저하-> useRef로 변경해야 하는가?

**Comment by KIMGEUNDU** [comment]
폰트, 이미지 최적화
질의응답방에서 문제 찾아볼것

**Comment by JOSuYeoM** [comment]
- 성능 최적화: 이미지, 페이지(suspend, 뤠이지..), 웹 폰트 (야무t routes 파일 참고)
- useState만 사용: 😶‍🌫️😶‍🌫️😶‍🌫️😶‍🌫️ debounce 함수 사용하여 리랜더링은 감소 -> 성능 이슈에는 딱히 ~ 체감상
- 페이지네이션: 리액트 쿼리 (질의응답 참고!)
- 재 배포 시 문제 발생-> 질문 게시판 이용!
- 옵티머스틱 업데이트? 옵티미스트릭? 
- 북마크- 리액트 쿼리?
