### ISSUE TITLE
🪄각 페이지 별 변경 사항

### ISSUE THREAD

**Issue by JOSuYeoM** [FRONTENDSCHOOL6/escape12#90]

**Comment by KIMGEUNDU** [comment]
🌙 다크모드

- [ ] Home
- [ ] LoginSelete
- [ ] Login
- [ ] Signup
- [ ] Theme
- [ ] RecordCommunity
- [ ] UploadRecord
- [ ] EditRecord
- [ ] ThemeRecord

**Comment by JOSuYeoM** [comment]
고생하셨습니다 😊😊😊😊
